services:
  - type: web
    name: my-app
    env: docker
    buildCommand: docker build -t my-app .
    startCommand: docker run my-app
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
